format = """
$username\
$hostname\
$directory\
$git_branch\
$git_state\
$git_status\
$cmd_duration\
$line_break\
$character"""

right_format = """
$time\
"""

add_newline = true

[directory]
truncation_length = 8
truncation_symbol = ".../"
style = "117"

[character]
success_symbol = "[❯](074)"
error_symbol = "[❯](204)"
vimcmd_symbol = "[❮](034)"

[git_branch]
format = "[$branch]($style)"
style = "250"

[git_status]
format = "[[(*$conflicted$untracked$modified$staged$renamed$deleted)](218) ($ahead_behind$stashed)]($style)"
style = "cyan"
conflicted = "​"
untracked = "​"
modified = "​"
staged = "​"
renamed = "​"
deleted = "​"
stashed = "≡"

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "bright-black"

[cmd_duration]
format = "[$duration]($style) "
style = "222"

[time]
disabled = false
time_format = "%R"
style = "250"
format = '[  $time]($style)'
