# import = [
#   "~/.config/alacritty/themes/themes/github_dark_high_contrast.toml"
# ]

live_config_reload = true

[env]
TERM = "xterm-256color"

[font]
size = 13

[font.bold]
family = "UDEV Gothic NFLG"
style = "Bold"

[font.bold_italic]
family = "UDEV Gothic NFLG"
style = "Bold Italic"

[font.glyph_offset]
x = 0
y = 0

[font.italic]
family = "UDEV Gothic NFLG"
style = "Italic"

[font.normal]
family = "UDEV Gothic NFLG"
style = "Regular"

[font.offset]
x = 0
y = 0

[scrolling]
history = 20000
multiplier = 3

[window]
decorations = "transparent"
dynamic_title = true
opacity = 0.5
startup_mode = "SimpleFullscreen"

[window.padding]
x = 8
y = 8

[window.dimensions]
columns = 200
lines = 60

[keyboard]
bindings = [
  { key = "Return", mods = "Command", action = "ToggleSimpleFullscreen" },
]
